# NumPy Fundamentals Lab

**Objective:** Practice fast numerical computing with NumPy and compare vectorized operations with pure Python.

In [3]:
import numpy as np
import time

print("NumPy version:", np.__version__)

NumPy version: 2.5.2


## 1. ndarray vs Python lists

In [4]:
py_list = [1, 2, 3, 4, 5]
arr = np.array([1, 2, 3, 4, 5], dtype=np.int64)

print("List:", py_list)
print("Array:", arr)
print("dtype:", arr.dtype)
print("shape:", arr.shape)
print("ndim:", arr.ndim)
print("size:", arr.size)

List: [1, 2, 3, 4, 5]
Array: [1 2 3 4 5]
dtype: int64
shape: (5,)
ndim: 1
size: 5


## 2. Creating arrays

In [5]:
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
range_arr = np.arange(0, 10, 2)
lin = np.linspace(0, 1, 6)
identity = np.eye(3)

print("zeros:\n", zeros)
print("ones:\n", ones)
print("arange:", range_arr)
print("linspace:", lin)
print("identity:\n", identity)

zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
arange: [0 2 4 6 8]
linspace: [0.  0.2 0.4 0.6 0.8 1. ]
identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 3. Indexing, slicing and boolean masks

In [6]:
a = np.arange(1, 13).reshape(3, 4)

print(a)
print("First row:", a[0])
print("Element [1,2]:", a[1, 2])
print("First two columns:\n", a[:, :2])

mask = a > 6
print("Values > 6:", a[mask])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Element [1,2]: 7
First two columns:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
Values > 6: [ 7  8  9 10 11 12]


## 4. Vectorization and broadcasting

In [7]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

print("x + y:", x + y)
print("x * 2:", x * 2)
print("x squared:", x ** 2)

matrix = np.arange(12).reshape(3, 4)
bias = np.array([1, 2, 3, 4])
print("Broadcasting result:\n", matrix + bias)

x + y: [11 22 33 44]
x * 2: [2 4 6 8]
x squared: [ 1  4  9 16]
Broadcasting result:
 [[ 1  3  5  7]
 [ 5  7  9 11]
 [ 9 11 13 15]]


## 5. Aggregations and axes

In [8]:
data = np.array([[10, 20, 30], [40, 50, 60]])

print("sum:", data.sum())
print("mean:", data.mean())
print("std:", data.std())
print("column sums:", data.sum(axis=0))
print("row sums:", data.sum(axis=1))
print("column means:", data.mean(axis=0))

sum: 210
mean: 35.0
std: 17.07825127659933
column sums: [50 70 90]
row sums: [ 60 150]
column means: [25. 35. 45.]


## 6. Reshaping and stacking

In [9]:
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)

print("Vertical stack:\n", np.vstack((a, b)))
print("Horizontal stack:\n", np.hstack((a, b)))
print("Reshaped:\n", np.arange(12).reshape(4, 3))

Vertical stack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontal stack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Reshaped:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## 7. Random numbers and basic linear algebra

In [10]:
rng = np.random.default_rng(42)

random_matrix = rng.normal(size=(3, 3))
random_vector = rng.normal(size=3)

print("Random matrix:\n", random_matrix)
print("Random vector:", random_vector)
print("Matrix-vector product:", random_matrix @ random_vector)
print("Transpose:\n", random_matrix.T)
print("Determinant:", np.linalg.det(random_matrix))

Random matrix:
 [[ 0.30471708 -1.03998411  0.7504512 ]
 [ 0.94056472 -1.95103519 -1.30217951]
 [ 0.1278404  -0.31624259 -0.01680116]]
Random vector: [-0.85304393  0.87939797  0.77779194]
Matrix-vector product: [-0.59080208 -3.53090413 -0.40022438]
Transpose:
 [[ 0.30471708  0.94056472  0.1278404 ]
 [-1.03998411 -1.95103519 -0.31624259]
 [ 0.7504512  -1.30217951 -0.01680116]]
Determinant: 0.005156749341926485


## 8. Vectorization speed comparison

The same computation is implemented with a Python loop and NumPy vectorization.

In [11]:
n = 1_000_000
values = list(range(n))
np_values = np.arange(n)

start = time.perf_counter()
python_result = [x * x + 2 * x + 1 for x in values]
python_time = time.perf_counter() - start

start = time.perf_counter()
numpy_result = np_values * np_values + 2 * np_values + 1
numpy_time = time.perf_counter() - start

print(f"Pure Python: {python_time:.6f} seconds")
print(f"NumPy:       {numpy_time:.6f} seconds")
print(f"Speedup:     {python_time / numpy_time:.2f}x")

Pure Python: 0.568084 seconds
NumPy:       0.021396 seconds
Speedup:     26.55x


## Conclusion

NumPy arrays provide compact typed storage and vectorized operations. Broadcasting allows operations between compatible shapes without explicit Python loops, while aggregation and linear algebra routines provide efficient numerical computation.